name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      # Also run the workflow when a pull request is labeled
      - labeled
      # Including the defaults of opened, synchronize, and reopened
      - opened
      - synchronize
      - reopened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby
        uses: ruby/setup-ruby@v1

      - name: Run
        run: |
          ruby main.rb
